using HR.LeaveManagement.Application.DTO.Common;
using HR.LeaveManagement.Domain.Enums;
using System;
using System.Collections.Generic;
using System.Text;

namespace HR.LeaveManagement.Application.DTO.LeaveType
{
    /// <summary>
    /// User is not allowed to set the Id while creating a Leave Type, it will be autogenerated by the Database
    /// </summary>
    public class CreateLeaveTypeDto:ILeaveTypeDto
    {
        public string LeaveTypeName { get; set; }
        public int AllocatedDays { get; set; }
    }
}
